#!/usr/bin/env ruby

require 'highline/import'
require_relative "lib/menu"
require_relative "lib/environment"

begin
  options = { environment: "production" }
  Environment.environment = options[:environment] || "production"
  Menu.top()
end